# Generated by Django 4.0.6 on 2022-10-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_fullname', models.CharField(help_text='seller_fullname', max_length=100)),
                ('seller_email', models.EmailField(help_text='seller_email', max_length=100)),
                ('seller_password', models.CharField(help_text='seller_password', max_length=200)),
                ('seller_contact', models.CharField(help_text='seller_contact', max_length=10)),
                ('seller_photo', models.ImageField(null=True, upload_to='sellerprofilephoto/')),
                ('seller_aadhar_photo', models.ImageField(null=True, upload_to='aadharphoto/')),
                ('seller_gst_photo', models.ImageField(null=True, upload_to='gstphoto/')),
                ('seller_status', models.CharField(default='pending', max_length=10)),
            ],
            options={
                'db_table': 'sellers_details',
            },
        ),
    ]
