# Generated by Django 4.0.6 on 2022-10-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='product_name', max_length=200)),
                ('product_model', models.CharField(help_text='product_model', max_length=200)),
                ('product_brand', models.CharField(help_text='product_brand', max_length=200)),
                ('product_category', models.CharField(help_text='product_category', max_length=200)),
                ('product_original_price', models.IntegerField(help_text='product_original_price', null=True)),
                ('product_discount_price', models.IntegerField(help_text='product_discount_price', null=True)),
                ('product_discount_percentage', models.CharField(help_text='product_discount_percentage', max_length=50, null=True)),
                ('product_photo1', models.ImageField(null=True, upload_to='images/')),
                ('product_photo2', models.ImageField(null=True, upload_to='images/')),
                ('product_photo3', models.ImageField(null=True, upload_to='images/')),
                ('product_photo4', models.ImageField(null=True, upload_to='images/')),
                ('product_photo5', models.ImageField(null=True, upload_to='images/')),
                ('product_review', models.TextField(max_length=800, null=True)),
                ('product_about', models.CharField(help_text='product_about', max_length=5000, null=True)),
                ('product_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='sellerapp.sellermodel')),
                ('product_wishlist', models.ManyToManyField(related_name='my_wishlist', to='customerapp.customermodel')),
            ],
            options={
                'db_table': 'products_details',
            },
        ),
    ]
