# Generated by Django 4.0.6 on 2022-10-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_wishlist',
            new_name='product_wishlist_action',
        ),
    ]
