# Generated by Django 4.0.6 on 2022-10-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_fullname', models.CharField(help_text='customer_fullname', max_length=50)),
                ('customer_contact', models.CharField(help_text='customer_contact', max_length=20)),
                ('customer_email', models.EmailField(help_text='customer_email', max_length=50)),
                ('customer_password', models.CharField(help_text='customer_password', max_length=50)),
                ('customer_address', models.CharField(help_text='customer_address', max_length=200, null=True)),
                ('customer_street', models.CharField(help_text='customer_street', max_length=50)),
                ('customer_city', models.CharField(help_text='customer_city', max_length=50)),
                ('customer_state', models.CharField(help_text='customer_state', max_length=50)),
                ('customer_pincode', models.CharField(help_text='customer_pincode', max_length=10, null=True)),
                ('customer_photo', models.ImageField(null=True, upload_to='images/')),
                ('customer_status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'db_table': 'customers_details',
            },
        ),
    ]
