# Generated by Django 4.0.6 on 2022-10-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_product_quantity', models.IntegerField(default=1, help_text='product_quantity', null=True)),
                ('cart_product_price', models.IntegerField(help_text='product_price', null=True)),
                ('cart_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_creator', to='customerapp.customermodel')),
                ('cart_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to='sellerapp.productmodel')),
                ('cart_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_seller', to='sellerapp.sellermodel')),
            ],
            options={
                'db_table': 'mycart_details',
            },
        ),
    ]
