# Generated by Django 4.0.6 on 2022-10-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0002_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModels',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_product_price', models.IntegerField(help_text='order_product_price', null=True)),
                ('order_product_quantity', models.IntegerField(help_text='order_product_quantity', null=True)),
                ('order_product_amount', models.IntegerField(help_text='order_product_amount', null=True)),
                ('order_date', models.DateTimeField(auto_now=True, help_text='order_date')),
                ('order_status', models.CharField(default='pending', help_text='order_status', max_length=300)),
                ('order_address', models.CharField(max_length=300, null=True)),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='customerapp.customermodel')),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_product_orders', to='sellerapp.productmodel')),
                ('order_product_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers_ordered_products', to='sellerapp.sellermodel')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
