# Generated by Django 4.0.6 on 2022-10-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0004_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedToFinalPaymentModel',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_product_photo', models.CharField(max_length=300, null=True)),
                ('payment_product_name', models.CharField(max_length=300, null=True)),
                ('payment_product_quantity', models.CharField(max_length=300, null=True)),
                ('payment_product_price', models.CharField(max_length=300, null=True)),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customermodel')),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productmodel')),
                ('sell_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.sellermodel')),
            ],
            options={
                'db_table': 'proceed_to_final_order',
            },
        ),
    ]
