# Generated by Django 4.0.6 on 2022-10-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_remove_feedbackmodel_ord_prod_comments_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='ordwise_comments',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='ordwise_expression',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='ordwise_rating',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='ordwise_sentiment',
        ),
        migrations.AlterModelTable(
            name='feedbackmodel',
            table='products_feedbacks',
        ),
    ]
