# Generated by Django 4.0.6 on 2022-10-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_remove_feedbackmodel_ordwise_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='ord_prodwise_comments',
        ),
    ]
