# Generated by Django 4.0.6 on 2022-10-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_remove_feedbackmodel_ord_prodwise_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='comment_id',
            new_name='productwise_feedback_id',
        ),
    ]
