# Generated by Django 4.0.6 on 2022-10-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0014_alter_orderreviewmodels_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='order_sentiment',
            field=models.CharField(help_text='ordersentiment', max_length=100, null=True),
        ),
    ]
