# Generated by Django 4.0.6 on 2022-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0015_alter_orderreviewmodels_order_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='order_rating',
            field=models.CharField(help_text='orderrating', max_length=100, null=True),
        ),
    ]
