# Generated by Django 4.0.6 on 2022-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0016_alter_orderreviewmodels_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='order_expression',
            field=models.CharField(help_text='orderexpression', max_length=100, null=True),
        ),
    ]
