# Generated by Django 4.0.6 on 2022-10-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0017_alter_orderreviewmodels_order_expression'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='prodwise_sentiment',
            new_name='psentiment',
        ),
        migrations.RenameField(
            model_name='orderreviewmodels',
            old_name='order_sentiment',
            new_name='osentiment',
        ),
    ]
