# Generated by Django 4.0.6 on 2022-10-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0018_rename_prodwise_sentiment_feedbackmodel_psentiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='custwise_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerwise_comments', to='customerapp.customermodel'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='prodwise_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productwise_comments', to='sellerapp.productmodel'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='prodwise_expression',
            field=models.CharField(help_text='productwise_expression', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='prodwise_rating',
            field=models.CharField(help_text='productwise_rating', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='psentiment',
            field=models.CharField(help_text='productwise_sentiment', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='sellwise_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerwise_comments', to='sellerapp.sellermodel'),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='customer_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cwise_comments', to='customerapp.customermodel'),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='order_expression',
            field=models.CharField(help_text='orderwise_expression', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='order_produt_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opwise_comments', to='customerapp.ordermodels'),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='order_rating',
            field=models.CharField(help_text='orderwise_rating', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='orderproduct_review',
            field=models.CharField(help_text='orderproduct_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='osentiment',
            field=models.CharField(help_text='orderwise_sentiment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='product_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pwise_comments', to='sellerapp.productmodel'),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='seller_comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swise_comments', to='sellerapp.sellermodel'),
        ),
    ]
