# Generated by Django 4.0.6 on 2022-10-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0020_alter_feedbackmodel_prodwise_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='productreview_date',
            field=models.DateTimeField(auto_now=True, help_text='productreview_date'),
        ),
    ]
