# Generated by Django 4.0.6 on 2022-10-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0022_alter_feedbackmodel_productwise_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orderid', to='customerapp.ordermodels'),
        ),
    ]
