# Generated by Django 4.0.6 on 2022-10-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0023_feedbackmodel_feedback_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='after_order_placed_revire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orderreview', to='customerapp.orderreviewmodels'),
        ),
    ]
