# Generated by Django 4.1.3 on 2022-12-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0027_feedbackmodel_feedback_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodels',
            name='order_seller_status',
            field=models.CharField(default='placed', help_text='order_seller_status', max_length=300),
        ),
    ]
