# Generated by Django 4.1.3 on 2022-12-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0028_ordermodels_order_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodels',
            name='ofeedback_block',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodels',
            name='osentiment_block',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordermodels',
            name='ouser_block',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
