# Generated by Django 4.0.6 on 2022-10-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0003_ordermodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordwise_comments', models.CharField(help_text='orderwisecomments', max_length=100)),
                ('prodwise_rating', models.CharField(help_text='productwiserating', max_length=100)),
                ('ordwise_rating', models.CharField(help_text='orderwiserating', max_length=100)),
                ('prodwise_expression', models.CharField(help_text='productwiseexpression', max_length=100)),
                ('ordwise_expression', models.CharField(help_text='orderwiseexpression', max_length=100)),
                ('prodwise_sentiment', models.CharField(help_text='productwisesentiment', max_length=100)),
                ('ordwise_sentiment', models.CharField(help_text='orderwisesentiment', max_length=100)),
                ('prodwise_comments_date', models.DateField(help_text='productwisecommentsdate', max_length=100)),
                ('ord_prod_comments_date', models.DateField(help_text='orderproductcommentsdate', max_length=100)),
                ('custwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerwisecomments', to='customerapp.customermodel')),
                ('ord_prodwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproductwisecomments', to='customerapp.ordermodels')),
                ('prodwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productwisecomments', to='sellerapp.productmodel')),
                ('sellwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerwisecomments', to='sellerapp.sellermodel')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
