# Generated by Django 4.0.6 on 2022-10-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_proceedtofinalpaymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='productwise_feedback',
            field=models.CharField(help_text='productwise_feedback', max_length=200, null=True),
        ),
    ]
