# Generated by Django 4.0.6 on 2022-10-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_feedbackmodel_productwise_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='ord_prod_comments_date',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='prodwise_comments_date',
        ),
    ]
