# Generated by Django 4.0.6 on 2022-10-13 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0010_rename_comment_id_feedbackmodel_productwise_feedback_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBasedFeedbackModel',
            fields=[
                ('orderwise_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderedproduct_feedback', models.CharField(help_text='orderedproductfeedback', max_length=100)),
                ('orderwise_rating', models.CharField(help_text='orderwise_rating', max_length=100)),
                ('orderwise_expression', models.CharField(help_text='orderwise_expression', max_length=100)),
                ('orderwise_sentiment', models.CharField(help_text='orderwise_sentiment', max_length=100)),
                ('customerwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerwise_comments', to='customerapp.customermodel')),
                ('ordered_produtwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_produtwise_comments', to='customerapp.ordermodels')),
                ('productwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productwise_comments', to='sellerapp.productmodel')),
                ('sellerwise_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellerwise_comments', to='sellerapp.sellermodel')),
            ],
        ),
    ]
