# Generated by Django 4.0.6 on 2022-10-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0011_orderbasedfeedbackmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbasedfeedbackmodel',
            old_name='orderwise_feedback_id',
            new_name='order_feedback_id',
        ),
    ]
