# Generated by Django 4.0.6 on 2022-10-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0012_rename_orderwise_feedback_id_orderbasedfeedbackmodel_order_feedback_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReviewModels',
            fields=[
                ('order_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderproduct_review', models.CharField(help_text='orderproductreview', max_length=100)),
                ('order_rating', models.CharField(help_text='orderrating', max_length=100)),
                ('order_expression', models.CharField(help_text='orderexpression', max_length=100)),
                ('order_sentiment', models.CharField(help_text='ordersentiment', max_length=100)),
                ('customer_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customercomments', to='customerapp.customermodel')),
                ('order_produt_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderprodutcomments', to='customerapp.ordermodels')),
                ('product_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productcomments', to='sellerapp.productmodel')),
                ('seller_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellercomments', to='sellerapp.sellermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderBasedFeedbackModel',
        ),
    ]
