# Generated by Django 4.0.6 on 2022-10-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0013_orderreviewmodels_delete_orderbasedfeedbackmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderreviewmodels',
            table='ordered_products_feedbacks',
        ),
    ]
