# Generated by Django 4.0.6 on 2022-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0019_alter_feedbackmodel_custwise_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='prodwise_rating',
            field=models.CharField(help_text='productwise_rating', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='psentiment',
            field=models.CharField(help_text='productwise_sentiment', max_length=100, null=True),
        ),
    ]
