# Generated by Django 4.0.6 on 2022-10-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0021_feedbackmodel_productreview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='productwise_feedback',
            field=models.CharField(help_text='productwise_feedback', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderreviewmodels',
            name='orderproduct_review',
            field=models.CharField(help_text='orderproduct_review', max_length=1000),
        ),
    ]
