# Generated by Django 4.0.6 on 2022-10-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_productmodel'),
        ('customerapp', '0024_feedbackmodel_after_order_placed_revire'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_wishlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='sellerapp.productmodel')),
            ],
            options={
                'db_table': 'wishlist_details',
            },
        ),
    ]
