# Generated by Django 4.1.3 on 2022-12-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0025_wishlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='prodwise_rating',
        ),
    ]
