# Generated by Django 4.1.3 on 2022-12-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0026_remove_feedbackmodel_prodwise_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_block',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='sentiment_block',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='user_block',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
