# Generated by Django 4.1.3 on 2022-12-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0029_ordermodels_ofeedback_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodels',
            name='qr_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
